In [1]:
import pandas as pd 

tweets = pd.read_csv('labeling data.csv')
tweets.head()

username         tanggal  \
0      pkmjangkar  3/7/2022 23:58   
1    CNNIndonesia  3/7/2022 23:57   
2  DindaNatasha15  3/7/2022 23:56   
3        juvejack  3/7/2022 23:49   
4    nengsunshine  3/7/2022 23:47   

                                               tweet sentimen  
0  update jadwal vaksinasi covid 19 upt puskesmas...  positif  
1  syarat jalan polymerase chain reaction antigen...   netral  
2  perintah pasti vaksin covid 19 bukti aman uji ...  positif  
3  menko maritim investasi luhut pandjaitan tanga...   netral  
4                     ok google negatif covid vaksin   netral

In [2]:
features = tweets.iloc[:, 2].values
labels = tweets.iloc[:, 3].values

## Mengekstrak fitur dan menyimpannya ke dalam future training matriks 

In [3]:
features_pp = []
for i in range(0, len(features)):
    feature_pp = (str(features[i]))
    features_pp.append(feature_pp)

## TfidfVectorizer

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk

from nltk.corpus import stopwords

vectorizer = TfidfVectorizer(max_features=2500, stop_words=stopwords.words('indonesian'))
features_pp = vectorizer.fit_transform(features_pp).toarray()

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:404: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['baiknya', 'berkali', 'kali', 'kurangnya', 'mata', 'olah', 'sekurang', 'setidak', 'tama', 'tidaknya'] not in stop_words.
  warnings.warn(


In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    features_pp, labels, test_size=0.2, random_state=42)

In [6]:
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [7]:
class KNN:
    def __init__(self,k=3):
        self.K=k
    def train(self,X,y):
        self.X_train=X
        self.y_train=y
    def predict(self,X):
        y_prediksi=[self._prediksi(x)for x in X]
        return np.array(y_prediksi)
    
    def _prediksi(self,x):
        #jarak kesemua data training
        jarak_titik=[self.jarak(x,x_train) for x_train in self.X_train]
        #urutkan jarak terdekat
        k_terbaik=np.argsort(jarak_titik)[:self.K]
        #ambil label
        label_k_terbaik=[self.y_train[i] for i in k_terbaik]
        #hasil yang banyak
        hasil_voting=Counter(label_k_terbaik).most_common(1)
        return hasil_voting[0][0]
        
        
    def jarak(self,x1,x2):
        return np.sqrt(np.sum((x1-x2)**2))

In [8]:
model=KNN(k=3)
model.train(X_train,y_train)
hasil =model.predict(X_test)
print(hasil)

['negatif' 'netral' 'netral' 'netral' 'netral' 'positif' 'netral' 'netral'
 'netral' 'netral' 'positif' 'positif' 'positif' 'netral' 'netral'
 'netral' 'netral' 'positif' 'netral' 'positif' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'negatif' 'positif' 'positif'
 'netral' 'netral' 'positif' 'negatif' 'netral' 'positif' 'netral'
 'netral' 'netral' 'netral' 'netral' 'positif' 'positif' 'netral'
 'negatif' 'negatif' 'netral' 'netral' 'negatif' 'netral' 'netral'
 'netral' 'positif' 'positif' 'negatif' 'positif' 'netral' 'netral'
 'netral' 'netral' 'positif' 'netral' 'positif' 'netral' 'netral' 'netral'
 'netral' 'negatif' 'netral' 'netral' 'netral' 'netral' 'netral' 'positif'
 'negatif' 'netral' 'negatif' 'negatif' 'positif' 'netral' 'netral'
 'netral' 'netral' 'netral' 'positif' 'netral' 'netral' 'positif' 'netral'
 'netral' 'negatif' 'netral' 'positif' 'netral' 'netral' 'netral' 'netral'
 'netral' 'positif' 'netral' 'negatif' 'negatif' 'negatif' 'netral'
 'netral' 'n

In [9]:
print(X_train)
#print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
akurasi=np.sum(hasil==y_test)/len(X_test)
print("akurasi",akurasi)

akurasi 0.784688995215311


In [11]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, hasil)

array([[ 12,  13,   4],
       [  7, 115,   9],
       [  5,   7,  37]], dtype=int64)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("\nConfusion Matrix")
print(confusion_matrix(y_test, hasil))

print("\nClassification Report")
print(classification_report(y_test, hasil))

print("\nAccuracy")
print(accuracy_score(y_test, hasil)*100, '%')


Confusion Matrix
[[ 12  13   4]
 [  7 115   9]
 [  5   7  37]]

Classification Report
              precision    recall  f1-score   support

     negatif       0.50      0.41      0.45        29
      netral       0.85      0.88      0.86       131
     positif       0.74      0.76      0.75        49

    accuracy                           0.78       209
   macro avg       0.70      0.68      0.69       209
weighted avg       0.78      0.78      0.78       209


Accuracy
78.4688995215311 %
